sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'controllers/**/*.js'
  - 'dojo/object/*.py'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'john-doe'
    - mtesauro
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
  - '@mtesauro'
